//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.Firebird.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.Firebird.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///select trim(rrf.rdb$field_name) field_name,
        ///f.rdb$field_type field_type, f.rdb$field_sub_type field_subtype, 
        ///f.rdb$field_length field_length
        ///from rdb$relation_fields rrf
        ///join rdb$fields f on f.rdb$field_name = rrf.rdb$field_source
        ///where rrf.rdb$relation_name = &apos;{0}&apos;.
        /// </summary>
        internal static string ColumnsQuery {
            get {
                return ResourceManager.GetString("ColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    trim(detail_index_segments.rdb$field_name) AS field_name,
        ///    trim(master_relation_constraints.rdb$relation_name) AS reference_table,
        ///    trim(master_index_segments.rdb$field_name) AS reference_field,
        ///    trim(detail_relation_constraints.rdb$constraint_name) AS constraint_name
        ///FROM
        ///    rdb$relation_constraints detail_relation_constraints
        ///    JOIN rdb$index_segments detail_index_segments ON detail_relation_constraints.rdb$index_name = detail_index_segments.rdb$index_name 
        ///    JOIN rdb$ref_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignKeyQuery {
            get {
                return ResourceManager.GetString("ForeignKeyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select trim(pp.rdb$parameter_name) parameter_name,
        ///pp.rdb$parameter_type parameter_direction,
        ///f.rdb$field_type field_type, f.rdb$field_sub_type field_subtype,
        ///f.rdb$field_length field_length,
        ///case
        ///    when pp.rdb$parameter_type=0 and
        ///    iif(pp.rdb$field_source starting with &apos;RDB$&apos;, f.rdb$default_source, pp.rdb$default_source) is not null then 1
        ///    else 0
        ///end is_optional,
        ///pp.rdb$parameter_number parameter_number
        ///from RDB$PROCEDURE_PARAMETERS pp
        ///join rdb$fields f on f.rdb$field_name = pp.rdb$fiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParametersQuery {
            get {
                return ResourceManager.GetString("ParametersQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ris.rdb$field_name field_name
        ///from rdb$relation_constraints rc
        ///join rdb$index_segments ris on rc.rdb$index_name = ris.rdb$index_name
        ///where rc.rdb$relation_name = &apos;{0}&apos; and rc.rdb$constraint_type = &apos;PRIMARY KEY&apos;.
        /// </summary>
        internal static string PrimaryKeyQuery {
            get {
                return ResourceManager.GetString("PrimaryKeyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///  trim(rp.rdb$procedure_name) AS procedure_name
        ///from
        ///  rdb$procedures rp
        ///where
        ///  rp.rdb$system_flag = 0.
        /// </summary>
        internal static string ProceduresQuery {
            get {
                return ResourceManager.GetString("ProceduresQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select trim(rdb$relation_name) table_name, iif(rdb$view_blr is not null,&apos;VIEW&apos;,&apos;TABLE&apos;) is_view
        ///from rdb$relations
        ///where (rdb$system_flag is null or rdb$system_flag = 0).
        /// </summary>
        internal static string TablesQuery {
            get {
                return ResourceManager.GetString("TablesQuery", resourceCulture);
            }
        }
    }
}
