//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.Firebird.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.Firebird.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TYPES_NUMBERS_NATURAL (
        ///    ID INTEGER NOT NULL,
        ///    TEST_INTEGER INTEGER,
        ///    TEST_SMALLINT SMALLINT,
        ///    TEST_BIGINT BIGINT);
        ///
        ///ALTER TABLE TYPES_NUMBERS_NATURAL
        ///ADD CONSTRAINT TYPES_NUMBERS_NATURAL
        ///PRIMARY KEY (ID);
        ///
        ///CREATE TABLE TYPES_NUMBERS_REAL (
        ///    ID INTEGER NOT NULL,
        ///    TEST_FLOAT FLOAT,
        ///    TEST_DOUBLE DOUBLE PRECISION,
        ///    TEST_NUMERIC_S NUMERIC(3,2),
        ///    TEST_NUMERIC NUMERIC(7,7),
        ///    TEST_NUMERIC_B NUMERIC(18,8),
        ///    TEST_DECIMAL_S DECIMAL(3,2),
        ///    TEST_DECIMAL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_db {
            get {
                return ResourceManager.GetString("create_db", resourceCulture);
            }
        }
    }
}
